import { Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, Menu, X } from 'lucide-react';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import produce from '@/assets/produce-hero.jpg';
import exportsPhoto from '@/assets/export-packaging.jpg';
import material from '@/assets/material-film.jpg';
import packhouse from '@/assets/packhouse.jpg';
import logo from '@/assets/aurestem-logo.png.asset.json';
import logoLight from '@/assets/aurestem-logo-light.png.asset.json';
export const images = { produce, exportsPhoto, material, packhouse };
export const pages = [ ['Solutions', '/solutions'], ['Technology', '/technology'], ['Industries', '/industries'], ['Innovation', '/innovation'], ['About', '/about'], ['Contact', '/contact'] ] as const;
export const contact = { email: 'sales@aurestem.com', phones: ['+91 7736 411143', '+91 7736 411146', '+91 7736 411149'], address: ['No.3, Nirmala Nilaya, Plot No. 5, Shastri Nagar,', 'K. Narayanapura Road, Thanisandra,', 'Bangalore, Karnataka, India - 560077.'] } as const;
export const telHref = (p: string) => `tel:${p.replace(/[^+\d]/g, '')}`;
export function Brand({ large = false }: { large?: boolean }) { return <span className={`brand brand-image ${large ? 'brand-large' : ''}`}><img src={large ? logoLight.url : logo.url} alt="AURESTEM" width={365} height={274} /></span>; }
export function Navbar() {
 const [open, setOpen] = useState(false); const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; const listener = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); if (e.key === 'Tab') { const links = menuRef.current?.querySelectorAll<HTMLElement>('a, button'); if (!links?.length) return; const first = links[0]; const last = links[links.length - 1]; if (!first || !last) return; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', listener); menuRef.current?.querySelector<HTMLElement>('a')?.focus(); return () => { document.body.style.overflow = old; document.removeEventListener('keydown', listener); }; }, [open]);
 return <header className="site-header"><div className="nav-inner"><Link to="/" aria-label="Aurestem home" onClick={() => setOpen(false)}><Brand /></Link><nav className="desktop-nav" aria-label="Main navigation">{pages.map(([name, path]) => <Link key={path} to={path} activeProps={{ className: 'nav-active' }}>{name}</Link>)}</nav><Button asChild className="nav-cta"><Link to="/contact">Talk to us <ArrowUpRight /></Link></Button><Button className="mobile-trigger" variant="ghost" size="icon" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <div ref={menuRef} id="mobile-menu" className="mobile-menu"><nav aria-label="Mobile navigation">{pages.map(([name, path], i) => <Link key={path} to={path} onClick={() => setOpen(false)}><span className="eyebrow">0{i + 1}</span>{name}<ArrowUpRight /></Link>)}<Button variant="outline" onClick={() => setOpen(false)}>Close menu <X /></Button></nav><p>Nature engineered through intelligent materials.</p></div>}</header>;
}
export function Footer() { return <footer className="site-footer"><div className="footer-main"><div><Link to="/" aria-label="Aurestem home"><Brand large /></Link><p>Advanced sustainable packaging for fresh<br className="desktop-only" /> produce and global supply chains.</p></div><nav aria-label="Footer navigation">{pages.map(([name,path]) => <Link key={path} to={path}>{name}<ArrowUpRight size={14}/></Link>)}</nav><div className="footer-details"><span className="eyebrow">START A CONVERSATION</span><Link to="/contact">Contact Aurestem <ArrowUpRight size={16}/></Link><span className="eyebrow">EMAIL</span><a className="footer-direct" href={`mailto:${contact.email}`}>{contact.email}</a><span className="eyebrow">PHONE</span><span className="phone-list">{contact.phones.map(p => <a key={p} className="footer-direct" href={telHref(p)}>{p}</a>)}</span><span className="eyebrow">OFFICE ADDRESS</span><address className="office-address">{contact.address.map(l => <span key={l}>{l}</span>)}</address><span className="eyebrow">SOCIAL</span><span className="footer-placeholder">LinkedIn — coming soon</span></div></div><div className="footer-bottom"><span>© {new Date().getUTCFullYear()} Aurestem. All rights reserved.</span><span>BIO MATERIALS × PACKAGING TECHNOLOGY</span><a href="#top">Back to top ↑</a></div></footer>; }
export function Action({ to = '/contact', children, outline = false }: { to?: '/contact' | '/solutions' | '/technology' | '/innovation' | '/industries' | '/about'; children: ReactNode; outline?: boolean }) { return <Button asChild variant={outline ? 'outline' : 'default'} className="action"><Link to={to}>{children}<ArrowUpRight /></Link></Button>; }
export function TextLink({ to, children }: { to: '/contact' | '/solutions' | '/technology' | '/innovation' | '/industries' | '/about'; children: ReactNode }) { return <Link className="text-link" to={to}>{children}<ArrowUpRight size={19}/></Link>; }
export function SectionHeader({ number, label, title, children }: { number: string; label: string; title: string; children?: ReactNode }) { return <div className="section-header"><div className="eyebrow"><span>{number}</span> / {label}</div><div><h2>{title}</h2>{children && <p>{children}</p>}</div></div>; }
export function PageIntro({ label, title, children }: { label: string; title: string; children: ReactNode }) { return <section className="page-intro container"><div className="eyebrow"><span className="status-dot"/> AURESTEM / {label}</div><h1>{title}</h1><p>{children}</p></section>; }
export function Photo({ src, alt, className = '' }: { src: string; alt: string; className?: string }) { return <div className={`photo ${className}`}><img src={src} alt={alt} loading="lazy" width={1536} height={1024}/></div>; }
export function CTASection() { return <section className="cta-section container"><div className="eyebrow">BETTER MATERIALS. BETTER POSSIBILITIES.</div><div className="cta-row"><h2>Let's build<br/>better packaging.</h2><div><p>Every product has a different journey.<br/>Let's find the right approach for yours.</p><Action>Talk to Aurestem</Action></div></div></section>; }
export function TechnologyDiagram() { return <div className="technology-diagram"><div className="diagram-top"><span className="eyebrow">CONTROLLED PACKAGING ENVIRONMENT</span><span className="eyebrow">FIG. 01</span></div><svg viewBox="0 0 660 340" role="img" aria-label="Conceptual diagram showing oxygen and carbon dioxide exchange through packaging film around fresh produce"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto"><path d="m0 0 6 3-6 3" fill="none" stroke="currentColor"/></marker></defs><rect x="100" y="105" width="460" height="180" rx="4" fill="none" stroke="currentColor" strokeWidth="1"/><path d="M100 115H560M100 124H560" fill="none" stroke="currentColor" strokeWidth=".5"/><path d="M195 44v140M335 180V44M475 44v140" fill="none" stroke="currentColor" strokeWidth="1" strokeDasharray="4 5" markerEnd="url(#arrow)"/><text x="182" y="29">O₂</text><text x="316" y="29">CO₂</text><text x="452" y="29">H₂O</text><g fill="none" stroke="currentColor" strokeWidth="1"><circle cx="210" cy="228" r="25"/><circle cx="251" cy="234" r="30"/><circle cx="300" cy="225" r="24"/><circle cx="352" cy="234" r="29"/><circle cx="402" cy="225" r="24"/><circle cx="447" cy="237" r="29"/></g><path d="M560 118h48M560 232h48" stroke="currentColor"/><text x="106" y="320">FRESH PRODUCE</text><text x="580" y="101">FILM</text></svg><div className="diagram-bottom"><span>Produce respiration</span><ArrowRight size={14}/><span>Material response</span><ArrowRight size={14}/><span>Freshness management</span></div><p className="diagram-note">Conceptual illustration. Material selection is application-specific.</p></div>; }
export function SolutionModule({ index, title, description, image, alt, tags, preview = false }: { index: string; title: string; description: string; image: string; alt: string; tags: string[]; preview?: boolean }) { return <article className={`solution-module ${index === '02' ? 'reverse' : ''}`}><Photo src={image} alt={alt}/><div className="solution-copy"><span className="solution-number">{index}</span><span className="eyebrow">ENGINEERED FOR YOUR APPLICATION</span><h3>{title}</h3><p>{description}</p><div className="material-tags">{tags.map(t => <span key={t}>{t}</span>)}</div><TextLink to={preview ? '/solutions' : '/contact'}>{preview ? 'Explore solution' : 'Discuss your requirements'}</TextLink></div></article>; }
export function meta(title: string, description: string) { return { meta: [{ title: `${title} — AURESTEM` }, { name: 'description', content: description }, { property: 'og:title', content: `${title} — AURESTEM` }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }; }
